# Generated by Django 6.0.3 on 2026-03-24 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile_address_profile_phone_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Мезгіл аты')),
                ('slug', models.SlugField(unique=True, verbose_name='URL сілтемесі')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тауар аты')),
                ('price', models.IntegerField(verbose_name='Бағасы')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Суреті')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='website.category')),
            ],
        ),
    ]
